export const ProjectPostsSummary = [
  {
    id: 1,
    category: "Frontend",
    section: "Project",
    projectTitle: "프로젝트 1",
    title: "프로젝트1 성능 개선",
    date: "2024-03-15",
    summary: "프로젝트1의 성능을 개선하는 방법에 대해 알아봅니다.",
    tags: ["프로젝트", "성능", "개선"],
    contentPath: "/posts/project/project1.md", // 마크다운 파일 경로
  },
  {
    id: 2,
    category: "Database",
    section: "Project",
    projectTitle: "프로젝트 2",
    title: "프로젝트2의 데이터 처리",
    date: "2024-03-10",
    summary: "프로젝트2에서 데이터 처리를 어떻게 하는지 알아봅니다.",
    tags: ["프로젝트", "데이터", "처리"],
    contentPath: "/posts/project/project2.md",
  },
  {
    id: 3,
    category: "Frontend",
    section: "Project",
    projectTitle: "프로젝트 3",
    title: "프로젝트3의 보안 강화",
    date: "2024-03-05",
    summary: "프로젝트3의 보안을 강화하는 방법에 대해 알아봅니다.",
    tags: ["프로젝트", "보안", "강화"],
    contentPath: "/posts/project/project3.md",
  },
  {
    id: 4,
    category: "Frontend",
    section: "Project",
    projectTitle: "FandomK",
    title: "조건부 렌더링 성능 최적화(디바운스, 스로틀)",
    date: "2024-11-07",
    summary: "조건부 렌더링 성능 최적화에 대해 알아봅니다.",
    tags: ["React", "성능", "최적화", "디바운스", "스로틀"],
    contentPath: "/posts/project/DebounceAndThrottle.md",
  },
  {
    id: 5,
    category: "Frontend",
    section: "Project",
    projectTitle: "FandomK",
    title: "무한스크롤 구현으로 데이터 불러오기",
    date: "2024-11-03",
    summary: "무한스크롤 구현으로 데이터를 불러오는 방법에 대해 알아봅니다.",
    tags: ["React", "무한스크롤", "커스텀훅", "성능"],
    contentPath: "/posts/project/InfiniteScrollPagination.md",
  },
  {
    id: 6,
    category: "Frontend",
    section: "Project",
    projectTitle: "Trend24",
    title: "react-rnd를 활용한 드래그 앤 드롭과 리사이징",
    date: "2024-06-21",
    summary: "드래그 앤 드롭과 리사이징",
    tags: ["React", "react-rnd", "드래그앤드롭", "리사이징"],
    contentPath: "/posts/project/ReactRnd.md",
  },
  {
    id: 7,
    category: "Frontend",
    section: "Project",
    projectTitle: "Trend24",
    title: "프로젝트에 GA4 연동하기",
    date: "2024-06-21",
    summary: "Google Analytics 4 연동하기",
    tags: ["React", "Google Analytics 4", "GA4"],
    contentPath: "/posts/project/GA4.md",
  },
  {
    id: 8,
    category: "Frontend",
    section: "Project",
    projectTitle: "Trend24",
    title: "Chart.js를 활용하여 데이터 시각화하기",
    date: "2024-06-21",
    summary: "데이터 시각화하기",
    tags: ["React", "Chart.js", "데이터시각화"],
    contentPath: "/posts/project/DataVisualizationChartJS.md",
  },
];
