export const StudyPostsSummary = [
  {
    id: 1,
    category: "Computer Science",
    section: "Study",
    title: "[알고리즘] 이진 탐색(Binary Search)",
    date: "2024-03-15",
    tags: ["알고리즘", "이진 탐색"],
    summary: "이진 탐색 알고리즘에 대해 알아봅니다.",
    contentPath: "/posts/study/BinarySearch.md",
  },
  {
    id: 2,
    category: "Computer Science",
    section: "Study",
    title: "[자료구조] 큐(Queue)",
    date: "2024-03-10",
    tags: ["자료구조", "큐"],
    summary: "큐 자료구조에 대해 알아봅니다.",
    contentPath: "/posts/study/Queue.md",
  },
  {
    id: 3,
    category: "Computer Science",
    section: "Study",
    title: "[자료구조] 스택(Stack)",
    date: "2024-03-05",
    tags: ["자료구조", "스택"],
    summary: "스택 자료구조에 대해 알아봅니다.",
    contentPath: "/posts/study/Stack.md",
  },
  {
    id: 4,
    category: "Computer Science",
    section: "Study",
    title: "[알고리즘] 빅오 표기법(Big O Notation)",
    date: "2024-08-25",
    tags: ["알고리즘", "빅오 표기법"],
    summary: "빅오 표기법",
    contentPath: "/posts/study/BigONotation.md",
  },
  {
    id: 5,
    category: "Computer Science",
    section: "Study",
    title: "[자료구조] 자바스크립트 배열과 객체의 성능",
    date: "2024-09-01",
    tags: ["자료구조", "배열", "객체", "성능", "JavaScript"],
    summary: "자바스크립트 배열과 객체의 성능",
    contentPath: "/posts/study/ArrayAndObject.md",
  },
];
