export const DevlifePostsSummary = [
  {
    id: 1,
    category: "Frontend",
    section: "Devlife",
    title: "React 18의 새로운 기능 탐구",
    date: "2024-03-15",
    tags: ["React", "Frontend"],
    summary: "React 18에서 추가된 주요 기능들을 자세히 알아봅니다.",
    contentPath: "/posts/devlife/React18NewFeatures.md",
  },
  {
    id: 2,
    category: "Frontend",
    section: "Devlife",
    title: "TypeScript 5.0 업데이트 리뷰",
    date: "2024-03-10",
    tags: ["TypeScript", "JavaScript"],
    summary: "TypeScript 5.0의 새로운 기능과 개선사항을 살펴봅니다.",
    contentPath: "/posts/devlife/TypeScript5.0UpdateReview.md",
  },
  {
    id: 3,
    category: "Frontend",
    section: "Devlife",
    title: "웹 성능 최적화 가이드",
    date: "2024-03-05",
    tags: ["Performance", "Web"],
    summary: "웹 애플리케이션의 성능을 개선하는 실전 가이드",
    contentPath: "/posts/devlife/WebPerformanceOptimizationGuide.md",
  },
  // {
  //   id: 4,
  //   category: "Frontend",
  //   section: "Devlife",
  //   title: "React 19",
  //   date: "2024-11-15",
  //   tags: ["React", "Frontend", "JavaScript"],
  //   summary: "React 19에서 새로운 기능과 변화",
  //   contentPath: "/posts/devlife/React19NewFeature.md",
  // },
];
