export const DevlifePostsSummary = [
  {
    id: 1,
    category: "Frontend",
    section: "Devlife",
    title: "React 18 주요 변경 사항",
    date: "2024-03-15",
    tags: ["React", "Frontend"],
    summary: "React 18에서 추가된 주요 기능들을 자세히 알아봅니다.",
    contentPath: `${
      import.meta.env.BASE_URL
    }/posts/devlife/React18NewFeatures.md`,
  },
  {
    id: 2,
    category: "Frontend",
    section: "Devlife",
    title: "useReducer Hook 사용법",
    date: "2024-03-21",
    tags: ["React", "Frontend", "JavaScript", "useReducer"],
    summary: "useReducer Hook의 사용법과 예제를 살펴봅니다.",
    contentPath: `${import.meta.env.BASE_URL}/posts/devlife/UseReducer.md`,
  },
  {
    id: 3,
    category: "Frontend",
    section: "Devlife",
    title: "TypeScript 5.0 업데이트 리뷰",
    date: "2024-05-10",
    tags: ["TypeScript", "JavaScript"],
    summary: "TypeScript 5.0의 새로운 기능과 개선사항을 살펴봅니다.",
    contentPath: `${
      import.meta.env.BASE_URL
    }/posts/devlife/TypeScript5.0UpdateReview.md`,
  },
  {
    id: 4,
    category: "Frontend",
    section: "Devlife",
    title: "웹 성능 최적화 가이드",
    date: "2024-05-15",
    tags: ["Performance", "Web"],
    summary: "웹 애플리케이션의 성능을 개선하는 실전 가이드",
    contentPath: `${
      import.meta.env.BASE_URL
    }/posts/devlife/WebPerformanceOptimizationGuide.md`,
  },

  {
    id: 5,
    category: "Frontend",
    section: "Devlife",
    title: "Next.js의 정적 생성(Static Generation)",
    date: "2024-11-15",
    tags: ["Next.js", "Frontend", "React"],
    summary: "Next.js의 정적 생성 기능을 사용하는 방법",
    contentPath: `${import.meta.env.BASE_URL}/posts/devlife/NextJSSG.md`,
  },
  {
    id: 6,
    category: "Frontend",
    section: "Devlife",
    title: "Next.js의 서버사이드 렌더링(Server Side Rendering)",
    date: "2024-11-15",
    tags: ["Next.js", "Frontend", "React"],
    summary: "Next.js의 서버사이드 렌더링 기능을 사용하는 방법",
    contentPath: `${import.meta.env.BASE_URL}/posts/devlife/NextJSSSR.md`,
  },
  {
    id: 7,
    category: "Frontend",
    section: "Devlife",
    title: "Next.js 의 렌더링 과정",
    date: "2024-11-20",
    tags: ["Next.js", "Frontend", "React"],
    summary: "Next.js의 렌더링 과정을 알아봅니다.",
    contentPath: `${import.meta.env.BASE_URL}/posts/devlife/NextJSRendering.md`,
  },

  {
    id: 10,
    category: "Frontend",
    section: "Devlife",
    title: "커밋 주기는 어느 정도로 해야 할까",
    date: "2024-12-02",
    tags: ["Git", "Commit"],
    summary: "커밋 주기에 대해 알아봅니다.",
    contentPath: `${import.meta.env.BASE_URL}/posts/devlife/CommitCycle.md`,
  },
  {
    id: 11,
    category: "Frontend",
    section: "Devlife",
    title: "Next.js 의 코드 스플리팅, 레이지 로딩",
    date: "2024-12-03",
    tags: ["Next.js", "Frontend", "React"],
    summary: "Next.js의 코드 스플리팅과 레이지 로딩 기능을 사용하는 방법",
    contentPath: `${
      import.meta.env.BASE_URL
    }/posts/devlife/NextJSCodeSplittingLazyLoading.md`,
  },
  {
    id: 12,
    category: "Frontend",
    section: "Devlife",
    title: "프론트엔드 개발에서 Next.js",
    date: "2024-12-03",
    tags: ["Next.js", "Frontend", "React"],
    summary: "프론트엔드 프레임워크",
    contentPath: `${
      import.meta.env.BASE_URL
    }/posts/devlife/NextJSinFrontend.md`,
  },
  {
    id: 13,
    category: "Frontend",
    section: "Devlife",
    title: "Why does JavaScript's fetch make me wait TWICE?",
    date: "2024-12-04",
    tags: ["JavaScript", "Fetch"],
    summary: "JavaScript의 fetch가 두번 기다리는 이유",
    contentPath: `${import.meta.env.BASE_URL}/posts/devlife/FetchTwiceinJS.md`,
  },
  {
    id: 14,
    category: "Frontend",
    section: "Devlife",
    title: "프론트엔드에서 대규모 트래픽 처리",
    date: "2024-12-04",
    tags: ["Frontend", "Traffic", "Next.js"],
    summary: "대규모 트래픽 처리",
    contentPath: `${
      import.meta.env.BASE_URL
    }/posts/devlife/LargeTrafficinFrontend.md`,
  },
  {
    id: 15,
    category: "Frontend",
    section: "Devlife",
    title: "React 19 주요 변경사항 총정리(1)",
    date: "2024-12-07",
    tags: ["React", "Frontend", "JavaScript", "React 19"],
    summary: "React 19의 새로운 점 정리",
    contentPath: `${import.meta.env.BASE_URL}/posts/devlife/React19_1.md`,
  },
  {
    id: 16,
    category: "Frontend",
    section: "Devlife",
    title: "React 19 주요 변경사항 총정리(2)",
    date: "2024-12-07",
    tags: ["React", "Frontend", "JavaScript", "React 19"],
    summary: "React 19의 개선된 점 정리",
    contentPath: `${import.meta.env.BASE_URL}/posts/devlife/React19_2.md`,
  },
];
